---
- name: Ubuntu desktop environment playbook
  # ansible-playbook ansible-linux-desktop.yml --ask-become-pass -vvv --check
  hosts: localhost
  roles:
    # Common roles
    - { role: linux-base, become: true }
    - { role: firewal, become: true }
    # Server roles
    - { role: docker, become: true }
    - { role: virt-kvm, become: true }
    # Desktop roles
    - { role: desktop, become: true }
    - { role: multimedia, become: true }
    - { role: kde, become: true }
