---
- name: Ubuntu desktop environment playbook
  # ansible-playbook ansible-linux-desktop.yml --ask-become-pass
  hosts: localhost
  roles:
    # Common roles
    - { role: linux-base, become: true }
    # Desktop roles
    #- { role: desktop, become: true }
